micronaut:
  application:
    name: task-manager
  caches:
    task-audit-logs-by-task:
      maximum-size: 1000
      expire-after-write: 10m
task:
  processing:
    start-delay: 1000
    processing-delay: 5000

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/task_manager
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9092